config/routes.rb
Rails.application.routes.draw do
  get 'expenses/index'
  get 'communities/index'
  get 'acts/index'
  get 'fees/index'

  
  resources :acts, only: [:index, :show]

  resources :fees, only: :index do
    resources :orders, only: :create
  end
  
  resources :orders, only: :index do
  	collection do
  		get 'clean'
  	end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount SimpleDiscussion::Engine => "/forum"
  
  devise_for :users, controllers: { registrations:
    "users/registrations" }
    
  root to: "communities#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/act.rb
class Act < ApplicationRecord
  belongs_to :community

  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 500 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user

  def self.init_payment(items, total)
    PayPal::SDK::REST::Payment.new({
      intent: "sale",
      payer: {
      payment_method: "paypal" },
      redirect_urls: {
          return_url: "http://localhost:3000/billings/execute",
          cancel_url: "http://localhost:3000/" },
      transactions: [{
          item_list: {
            items:items
            },
          amount: {
            total: total.to_s,
            currency: "USD" },
            description: "Compra desde E-commerce Rails." }]
      })
  end

  def self.execute_payment(current_user, payment_id, payer_id)
    paypal_payment = PayPal::SDK::REST::Payment.find(payment_id)
   
    return false unless paypal_payment.execute(payer_id: payer_id)
   
    amount = paypal_payment.transactions.first.amount.total
   
    billing = Billing.create(
      user: current_user,
      code: paypal_payment.id,
      payment_method: 'paypal',
      amount: amount,
      currency: 'USD'
    )
   
    if billing.persisted?
      current_user.orders.cart.update_all(payed: true, billing_id: billing.id)
      true
    else
      false
    end
  end

end

app/models/community.rb
class Community < ApplicationRecord
    has_many :users, dependent: :destroy
    has_many :expenses, dependent: :destroy
    has_many :acts, dependent: :destroy

    validates :name, uniqueness: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :community

  validates :value, numericality: true
  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 500 }
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :user
  scope :unpayed , -> { where(payed: false)}
  scope :payed_yes , -> { where(payed: true)}

  validates :value, numericality: true
  validates :fees_date, presence: true


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :fee
  belongs_to :billing, optional: true

  validates :price, numericality: true

  scope :cart, (-> {where(payed: false)})

  def self.to_paypal_items
    where(nil).map do |order|
      item = {}
      item[:name] = order.fee.fees_date
      item[:sku] = order.id.to_s
      item[:price] = order.price.to_s
      item[:currency] = 'USD'
      item[:quantity] = 1
      item
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }


  include SimpleDiscussion::ForumUser

  belongs_to :community 
  
  has_many :fees, dependent: :destroy
  has_many :orders

  has_one_attached :image
  
  scope :by_community, ->(community_id) { where("community_id = ?", community_id)}

  def name
    "#{email}"
  end
  
  def self.unpayed_fees_by_community(community_id)
    unpayed_fees = []
    users = by_community(community_id)
    users.each do |user|
      user.fees.unpayed.each do |fee|
        unpayed_fees << fee.value
      end
    end
    return unpayed_fees
  end

  def self.payed_fees_by_community(community_id)
    payed_fees = []
    users = by_community(community_id)
    users.each do |user|
      user.fees.payed_yes.each do |fee|
        payed_fees << fee.value
      end
    end
    return payed_fees
  end

         
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

    def index
        acts = Act.all
        @user = current_user    
    end

    def show
        @act = Act.find(params[:id])
    end

    
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

    def pre_pay
        orders = current_user.orders.cart
        total = orders.pluck("price").sum()
        items = orders.to_paypal_items
        payment = Billing.init_payment(items, total)
        
        if payment.create
            redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
            redirect_to redirect_url
        else
            render json: payment.error
        end
    end

    def execute
        if Billing.execute_payment(current_user, params[:paymentId], params[:PayerID])
        redirect_to root_path, notice: "El pago se realizó con éxito!"
        else
        render plain: "No se puedo generar el cobro en PayPal."
        end
    end

end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
    end
    
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    
  
    def create
      p = Fee.find(params[:fee_id])
      o = Order.find_or_create_by(user: current_user, fee: p, payed: false, price: p.value)
  
      if o.save
        respond_to do |format|
          format.js { flash.now[:notice] = "Tu cuota ha sido agregada al carro" }
        end
        
      else
        redirect_to fees_path, alert: "Tu cuota NO ha sido agregada al carro"
      end
    end
  
    def clean
      @orders = Order.where(user: current_user, payed: false)
      @orders.destroy_all
      redirect_to orders_path, notice: 'El carro se ha vaciado.'
    end
  
    def index
      @orders = current_user.orders.where(payed: false)
      @total = @orders.pluck("price").sum()
      @user = current_user
    end
  end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sinergy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# ----------------------FAVICON -------------------- %>    
    <link rel="icon" type="image/png" href="https://i.imgur.com/z5Wb86P.png">
    <%# ----------------------VIEWPORT -------------------- %>    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# ----------------------BOOSTRAP -------------------- %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%# ----------------------FONTS-------------------------- %>
    <script src="https://kit.fontawesome.com/0d8ed9d80c.js" crossorigin="anonymous"></script>
    <%# -------------------JQUERY------------------------ %>
    <script  src="https://code.jquery.com/jquery-3.4.1.js"  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="  crossorigin="anonymous"></script>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
      <% if user_signed_in? %>
        <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4">
         <%= render 'shared/navbar' %>
         <%= render 'shared/flash_messages' %>
         <%= render 'shared/sidebar' %>
         <%= yield %>
        </main>
      <% else%>
        <main class="container-fluid">
          <%= render 'shared/navbar' %>
          <%= render 'shared/flash_messages' %>  
          <%= yield %>
        </main>
      <% end %>
  </body>
</html>

app/views/layouts/simple_discussion.html.erb
<div class="row col-md-12">
  <h1>
    <%= t('community') %>
  </h1>
</div>

<div class="row simple_discussion">
  <div class="col-md-3 mb-3">

    <div class="card card-body">
      <%= link_to t('ask_a_question'), simple_discussion.new_forum_thread_path, class: "btn btn-outline-primary btn-block" %>
      <hr />

      <div class="forum-thread-filters">
        <h5>
          <strong>
            <%= t('filters') %>
          </strong>
        </h5>
        <div>
          <%= forum_link_to simple_discussion.forum_threads_path, exact: true do %>
            <%= icon "bars" %>
            <%= t('.all_threads') %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div>
            <%= forum_link_to simple_discussion.mine_forum_threads_path do %><%= icon "user-circle-o" %>
              <%= t('.my_questions') %>
            <% end %>
          </div>
          <div>
            <%= forum_link_to simple_discussion.participating_forum_threads_path do %>
              <%= icon "comments-o" %>
              <%= t('.participating') %>
            <% end %>
          </div>
        <% end %>
        <div>
          <%= forum_link_to simple_discussion.answered_forum_threads_path do %>
            <%= icon "check" %>
            <%= t('.answered') %>
          <% end %>
        </div>
        <div>
          <%= forum_link_to simple_discussion.unanswered_forum_threads_path do %>
            <%= icon "question" %>
            <%= t('.unanswered') %>
          <% end %>
        </div>
      </div>

      <hr />

      <div class="forum-thread-filters">
        <h6>
          <strong>
            <%= t('.by_category') %>
          </strong>
        </h6>
        <div><%= forum_link_to simple_discussion.forum_threads_path, exact: true do %><%= icon "circle" %> All<% end %></div>
        <% ForumCategory.sorted.each do |category| %>
          <div>
            <%= forum_link_to simple_discussion.forum_category_forum_threads_path(category) do %>
              <%= icon "circle", style: "color: #{category.color}" %>
              <%= category.name %>
            <% end %>
          </div>
        <% end %>
      </div>

      <% if @forum_thread.present? && @forum_thread.persisted? %>
        <hr />

        <%# User has not posted in the thread or subscribed %>
        <h5><%= t('.notifications') %></h5>

        <%= link_to simple_discussion.forum_thread_notifications_path(@forum_thread), method: :post, class: "btn btn-secondary btn-sm btn-block mb-2" do %>
          <% if @forum_thread.subscribed? current_user %>
            <%= icon "bell-slash" %> Unsubscribe
          <% else %>
            <%= icon "bell" %>
            <%= t('.suscribe') %>
          <% end %>
        <% end %>

        <small><%= @forum_thread.subscribed_reason(current_user) %></small>
      <% end %>
    </div>

  </div>

  <div class="col-md-9 mb-3">

    <div class="card card-body">
      <%= yield %>
    </div>

  </div>
</div>

<% parent_layout("application") %>

app/views/shared/_chart.html.erb
<%= pie_chart @user.fees.group(:payed).count %>

app/views/shared/_flash_messages.html.erb
<div id="flash">
    <% if alert.present? %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar ">
 <%= link_to image_tag("https://svgshare.com/i/FNW.svg", alt:"Brand"), root_path, :class=>'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to "Admin", new_admin_user_session_path, class:"nav-link"%>

  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav ">
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle "  href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if user_signed_in? %>
             <%= current_user.email %>
          <% else %>
             Ingresar
          <% end %>
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdownMenuLink">
          <% if user_signed_in? %>
            <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"dropdown-item"%>
          <% else %>
            <%= link_to "Ingreso", new_user_session_path, class:"dropdown-item"%>
            <%= link_to "Registro", new_user_registration_path, class:"dropdown-item"%>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="page-wrapper chiller-theme toggled">
  <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <i class="fas fa-bars"></i>
  </a>
  <nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
      <div class="sidebar-brand">
        <a href="/communities/index">
         <%= link_to image_tag("https://svgshare.com/i/FNW.svg", alt:"Brand", size: "150x50"), root_path, :class=>'navbar-brand' %>
         </a>
        <div id="close-sidebar">
          <i class="fas fa-times"></i>
        </div>
      </div>
      <div class="sidebar-header">
        <div class="user-pic">
        <% if @user.image.attached? %>
            <%= image_tag @user.image, class:'img-responsive img-rounded' %>
        <% else %>
            <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg" alt="User picture">
        <% end %>
        </div>
        <div class="user-info">
          <span class="user-name"><%= @user.email %>
            <strong></strong>
          </span>
          <span class="user-role">Administrator</span>
          <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
        </div>
      </div>
      <!-- sidebar-header  -->
      <%# <div class="sidebar-search">
        <div>
          <div class="input-group">
            <input type="text" class="form-control search-menu" placeholder="Search...">
            <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
            </div>
          </div>
        </div>
      </div> %>
      <div class="sidebar-menu">
        <ul>
          <li class="header-menu">
            <span>General</span>
          </li>
          <li class="sidebar-item">
            <a href="/communities/index">
              <i class="fa fa-tachometer-alt"></i>
              <span>Dashboard</span>
              <%# <span class="badge badge-pill badge-warning">New</span> %>
            </a>
          </li>
          <li class="sidebar-item">
            <a href="/fees/index">
              <i class="fas fa-wallet"></i>
              <span>Mis cuotas</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a href="/expenses/index">
              <i class="fas fa-shopping-cart"></i>
              <span>Gastos</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a href="/acts/index">
              <i class="fas fa-file-contract"></i>
              <span>Actas</span>
            </a>
          </li>
          <li class="sidebar-item">
            <a href="<%= simple_discussion_path%>">
              <i class="far fa-comments"></i>
              <span>Foro</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
      <a href="#">
        <i class="fas fa-bell"></i>
        <span class="badge badge-pill badge-warning notification">3</span>
      </a>
      <a href="#">
        <i class="fa fa-envelope"></i>
        <span class="badge badge-pill badge-success notification">7</span>
      </a>
      <a href="#">
        <i class="fa fa-cog"></i>
        <span class="badge-sonar"></span>
      </a>
      <a href="#">
        <i class="fa fa-power-off"></i>
      </a>
    </div>
  </nav>
</div>
<!-- page-wrapper -->
    <script>
    jQuery(function ($) {

        $(".sidebar-dropdown > a").click(function() {
      $(".sidebar-submenu").slideUp(200);
      if (
        $(this)
          .parent()
          .hasClass("active")
      ) {
        $(".sidebar-dropdown").removeClass("active");
        $(this)
          .parent()
          .removeClass("active");
      } else {
        $(".sidebar-dropdown").removeClass("active");
        $(this)
          .next(".sidebar-submenu")
          .slideDown(200);
        $(this)
          .parent()
          .addClass("active");
      }
    });

    $("#close-sidebar").click(function() {
      $(".page-wrapper").removeClass("toggled");
    });
    $("#show-sidebar").click(function() {
      $(".page-wrapper").addClass("toggled");
    });




    });
  </script>

app/views/shared/_spacer.html.erb
<hr/>