config/routes.rb
Rails.application.routes.draw do
  get 'expenses/index'
  get 'communities/index'
  get 'acts/index'
  get 'fees/index'

  
  resources :acts, only: [:index, :show]

  resources :fees, only: :index do
    resources :orders, only: :create
  end
  
  resources :orders, only: :index do
  	collection do
  		get 'clean'
  	end
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount SimpleDiscussion::Engine => "/forum"
  
  devise_for :users, controllers: { registrations:
    "users/registrations" }
    
  root to: "communities#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/act.rb
class Act < ApplicationRecord
  belongs_to :community

  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 500 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user

  def self.init_payment(items, total)
    PayPal::SDK::REST::Payment.new({
      intent: "sale",
      payer: {
      payment_method: "paypal" },
      redirect_urls: {
          return_url: "http://localhost:3000/billings/execute",
          cancel_url: "http://localhost:3000/" },
      transactions: [{
          item_list: {
            items:items
            },
          amount: {
            total: total.to_s,
            currency: "USD" },
            description: "Compra desde E-commerce Rails." }]
      })
  end

  def self.execute_payment(current_user, payment_id, payer_id)
    paypal_payment = PayPal::SDK::REST::Payment.find(payment_id)
   
    return false unless paypal_payment.execute(payer_id: payer_id)
   
    amount = paypal_payment.transactions.first.amount.total
   
    billing = Billing.create(
      user: current_user,
      code: paypal_payment.id,
      payment_method: 'paypal',
      amount: amount,
      currency: 'USD'
    )
   
    if billing.persisted?
      current_user.orders.cart.update_all(payed: true, billing_id: billing.id)
      true
    else
      false
    end
  end

end

app/models/community.rb
class Community < ApplicationRecord
    has_many :users, dependent: :destroy
    has_many :expenses, dependent: :destroy
    has_many :acts, dependent: :destroy

    validates :name, uniqueness: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :community

  validates :value, numericality: true
  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 500 }
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :user
  scope :unpayed , -> { where(payed: false)}
  scope :payed_yes , -> { where(payed: true)}

  validates :value, numericality: true
  validates :fees_date, presence: true


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :fee
  belongs_to :billing, optional: true

  validates :price, numericality: true

  scope :cart, (-> {where(payed: false)})

  def self.to_paypal_items
    where(nil).map do |order|
      item = {}
      item[:name] = order.fee.fees_date
      item[:sku] = order.id.to_s
      item[:price] = order.price.to_s
      item[:currency] = 'USD'
      item[:quantity] = 1
      item
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }


  include SimpleDiscussion::ForumUser

  belongs_to :community 
  
  has_many :fees, dependent: :destroy
  has_many :orders

  has_one_attached :image
  
  scope :by_community, ->(community_id) { where("community_id = ?", community_id)}

  def name
    "#{email}"
  end
  
  def self.unpayed_fees_by_community(community_id)
    unpayed_fees = []
    users = by_community(community_id)
    users.each do |user|
      user.fees.unpayed.each do |fee|
        unpayed_fees << fee.value
      end
    end
    return unpayed_fees
  end

  def self.payed_fees_by_community(community_id)
    payed_fees = []
    users = by_community(community_id)
    users.each do |user|
      user.fees.payed_yes.each do |fee|
        payed_fees << fee.value
      end
    end
    return payed_fees
  end

         
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

    def index
        acts = Act.all
        @user = current_user    
    end

    def show
        @act = Act.find(params[:id])
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :name])
    end
  end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

    def pre_pay
        orders = current_user.orders.cart
        total = orders.pluck("price").sum()
        items = orders.to_paypal_items
        payment = Billing.init_payment(items, total)
        
        if payment.create
            redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
            redirect_to redirect_url
        else
            render json: payment.error
        end
    end

    def execute
        if Billing.execute_payment(current_user, params[:paymentId], params[:PayerID])
        redirect_to root_path, notice: "El pago se realizó con éxito!"
        else
        render plain: "No se puedo generar el cobro en PayPal."
        end
    end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_user!

  def index
      @user = current_user
      @users = User.all
      @community = @user.community_id
      
      @unpayed_fees = User.unpayed_fees_by_community(current_user.community_id)
      @payed_fees = User.payed_fees_by_community(current_user.community_id)
      @total_payed_fees = @payed_fees.inject  {|sum, fee| sum + fee}
      @total_unpayed_fees = @unpayed_fees.inject  {|sum, fee| sum + fee}

      @expenses_values = @user.community.expenses.pluck('value')
      @total_expenses = @expenses_values.sum
      @available = @total_payed_fees - @total_expenses
    end
  
  
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
    end
    
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    
  
    def create
      p = Fee.find(params[:fee_id])
      o = Order.find_or_create_by(user: current_user, fee: p, payed: false, price: p.value)
  
      if o.save
        respond_to do |format|
          format.js { flash.now[:notice] = "Tu cuota ha sido agregada al carro" }
        end
        
      else
        redirect_to fees_path, alert: "Tu cuota NO ha sido agregada al carro"
      end
    end
  
    def clean
      @orders = Order.where(user: current_user, payed: false)
      @orders.destroy_all
      redirect_to orders_path, notice: 'El carro se ha vaciado.'
    end
  
    def index
      @orders = current_user.orders.where(payed: false)
      @total = @orders.pluck("price").sum()
      @user = current_user
    end
  end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/acts/_acts.html.erb
<% @user.community.acts.each do |acts| %>
    <div class="card mb-3 border-success bg-dark text-white" style="max-width: 540px;">
        <div class="row">
            <div class="col-md-4">
                <%= link_to acts, data: {remote: true} do %>
                    <%= image_tag acts.photo, size: "200x250", class:"card-img" %>
                <% end %>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title"><%= acts.name %></h5>
                    <hr>
                    <p class="card-text"><%= acts.description %></p>
                </div>
            </div>          
        </div>
        <div class="card-footer bg-secondary justify-content-end">
         <small class="text-white"><%= acts.date %></small>
        </div>
    </div>
<% end %>

app/views/acts/_show.html.erb
<%= image_tag @act.photo, size: "1000x600", class:"card-img" %>

app/views/acts/index.html.erb
<h3><i class="fas fa-file-contract"></i> actas </h3>  
<%= render "acts"%>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/acts/show.js.erb
$('.modal-body').html("<%= j render 'show' %>")
$('#myModal').modal('show')

app/views/communities/index.html.erb
<div class="row">
    <div class="col-8">
        <div class="card bg-transparent">
        <div class="card-header">
            <h3><i class="fas fa-chart-pie"></i> Cuotas pagadas y no pagadas</h3>
        </div>
        <div class="card-body">
            <p class="card-text"><%= render 'shared/chart' %></p>
            <a href="/fees/index" class="btn btn-primary"><i class="fas fa-wallet"></i> Mis cuotas</a>
        </div>
        </div>
        
    </div>
    <div class="col-4">
        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
        <div class="card-header">Dinero disponible</div>
        <div class="card-body">
            <p class="card-text"><%= number_to_currency(@available, precision: 0) %></p>
        </div>
        </div>

        <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
        <div class="card-header">Dinero Recaudado en total</div>
        <div class="card-body">
            <p class="card-text"><%= number_to_currency(@total_payed_fees, precision: 0) %></p>
        </div>
        </div>

        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
        <div class="card-header">Deuda de la comunidad</div>
        <div class="card-body">
            <p class="card-text"><%= number_to_currency(@total_unpayed_fees, precision: 0) %></p>
        </div>
        </div>
    </div>
</div>

app/views/fees/index.html.erb
<div class="row">
  <div class="col-8">
    <h3><i class="fas fa-wallet"></i> Mis cuotas </h3>
    <table class="table table-striped table-dark fees-table">
      <thead>
        <tr>
          <th scope="col">Fecha cuota</th>
          <th scope="col">Valor cuota</th>
          <th scope="col">Estado de pago</th>
          <th scope="col">Agregar al carro</th>
        </tr>
      </thead>
      <tbody>
        <% @user.fees.each do |fees| %>
          <tr>
          <td><%= fees.fees_date.strftime("%m - %Y") %></td>
          <td><%= number_to_currency(fees.value, precision: 0) %></td>
          <td><%= fees.payed %></td>
          <% if fees.payed == false %>
            <td class= 'btn btn-success btn_payed'  data-fee="<%= fees.id %>">Agregar al carro</td>
          <% else %> 
            <td> Cuota Pagada </td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-4">
    <h3><i class="fab fa-cc-paypal"></i> Paga Online </h3>
    <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
    <div class="card-header">Pagar</div>
    <div class="card-body">
      <a class="nav-link btn btn-warning" href="<%= orders_path %>">Mi carro <span class="sr-only">(current)</span></a>
    </div>
  </div>
</div>

<script>
$(".btn_payed").on('click', function(e){
  e.preventDefault()
   var fee_id = $(this).data('fee')
   $(this).text('Cuota en proceso de pago')
    $.ajax({
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token',  $('meta[name="csrf-token"]').attr('content'))},
    url: '/fees/'+ fee_id + '/orders',
    type: 'POST',
    dataType: 'script'
    })
  })
</script>

app/views/orders/create.js.erb
$("#flash").html('<%= j render partial: "shared/flash_messages" %>');

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <h3><i class="fas fa-shopping-cart"></i> Carro de pago de cuotas </h3>
    <table class="table table-striped table-dark col-6 fees-table">
      <thead>
        <tr>
          <th scope="col">Fecha cuota</th>
          <th scope="col">Valor</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td> <%= order.fee.fees_date.strftime("%m - %Y") %> </td>
            <td> <%= order.price %></td>
          </tr>
        <% end %>
        <tr class="table-dark">
        <td><strong>Total de la compra:</strong></td>
        <td><strong><%= @total %></strong></td>
        </tr>
      </tbody>
    </table>
    <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-outline-danger'  %>
    <%= link_to 'Confirmar pago', pre_pay_billings_path, class: 'btn btn-success' %> 

  <% else %>
    <p>No tienes cuotas por pagar.</p>
<% end %>
</div>